blueprint:
  name: HomePods als Türklingel
  description: "Spielt einen Klingelton auf HomePods ab, wenn die Türklingel gedrückt wird."
  domain: automation
  input:
    doorbell_trigger:
      name: Türklingel-Trigger
      description: "Das Gerät, das als Türklingel fungiert. (z. B. Button oder Bewegungssensor)"
      selector:
        entity:
          domain:
            - binary_sensor
            - device_tracker
            - sensor
    homepods:
      name: HomePods oder AirPlay-Lautsprecher
      description: "Die HomePods, die den Klingelton abspielen sollen."
      selector:
        device:
          integration: homekit
          multiple: true
    volume:
      name: Lautstärke
      description: "Die Lautstärke des Klingeltons (0.1 - 1.0)"
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          unit_of_measurement: "Lautstärke"
    ringtone:
      name: Klingelton
      description: "Pfad zur MP3-Datei für den Klingelton. Standard: /config/audio/doorbell-2.mp3"
      default: "/config/audio/doorbell-2.mp3"
      selector:
        text:

mode: restart

trigger:
  - platform: state
    entity_id: !input doorbell_trigger
    to: "on"

action:
  - repeat:
      for_each: !input homepods
      sequence:
        - service: media_player.volume_set
          data:
            entity_id: "{{ device_entities(repeat.item) | select('search', 'media_player') | list | first }}"
            volume_level: !input volume
        - service: media_player.play_media
          data:
            entity_id: "{{ device_entities(repeat.item) | select('search', 'media_player') | list | first }}"
            media_content_id: !input ringtone
            media_content_type: "music"